NAME     := am
SRCS      = $(addprefix src/, $(AM_SRCS))
INC_PATH += $(AM_HOME)/am/src

### Clean a single project (remove `build/`)
# clean:
# 	rm -rf Makefile.html $(WORK_DIR)/build/
# .PHONY: clean

include $(AM_HOME)/Makefile
